baseurl = "https://www.runlvl6.com/"
languageCode = "en-us"
theme = "hugo-steam-theme"
disqusShortname = ""
# Enable Google Analytics be inserting your tracking code
googleAnalytics = ""
# Number of posts per page
paginate = 5

[params]
    title = "Run Lvl 6"
    subtitle = "Inner Ramblings Of A Rebooting, Learning Developer & Optimistic ~~Pessimist~~"
    copyright = ""

    useSummaryIfNoDescription = true

    # You can choose between green, orange, red and blue.
    themecolor = "green"

    # Link custom assets relative to /static
    favicon   = "favicon.ico"
    customCSS = []
    customJS  = []

    # To provide some metadata for search engines and the about section in the footer
    # feel free to add a few information about you and your website.
    name = "Keyasha B"
    bio = "developer - creator - sugar aficionado"
    description = "A WOC in tech software developer documenting my journey learning swift, ruby, ios and tech"
    
    # Link your social networks (optional)
    location = ""
    twitter = "kbrunlvl6"
    linkedin = ""
    googleplus = ""
    facebook = ""
    instagram = ""
    github = "KMBrothern"
    gitlab = ""
    bitbucket = ""

    # Customize or translate the strings
    keepReadingStr = "Keep reading"
    backtotopStr = "Back to top"
    shareStr = "Share"
    pageNotFoundTitle = "404 - Page not found"